Create sprint9.md
HumanLearning2021/HumanLearningApp pull request #170
Opened 2021-05-13 11:53 UTC by Nitwix

Please add your summary to this PR, as usual.

2021-05-13 14:27 UTC, NicolasVial commented on summaries/sprint9.md
> +
```suggestion
## Vial, Nicolas
This week I made the necessary changes to the interfaces to allow a separation between user and administrator.  There were fewer changes to make than I thought, so I worked a little less than usual this week. My task was dependent on Marouane's who was in charge of the backend, so we communicated a lot to agree on the model used. I thought I would have time to start writing the documentation for all dataset editing interfaces but I didn't find the time. I didn't have any problems except a problem of understanding about injections that Louis helped me to clarify.
```

2021-05-13 19:22 UTC, lourkeur approved these changes

2021-05-14 06:18 UTC, jonaskon requested changes
Missing scrum master review

2021-05-14 06:53 UTC, jonaskon approved these changes

2021-05-15 09:35 UTC, merged