Refactor/177 Flatten POKO hierarchy
HumanLearning2021/HumanLearningApp pull request #180
Opened 2021-05-14 08:50 UTC by lourkeur

For #177 I'm going to submit multiple PRs in increasing order of invasiveness.

This PR flattens the POKO hierarchy as recommended in the code review.

Note: It adds a ton of deprecation warnings. That's so as to minimize the amount of lines touched and potential conflicts. At some point where we have no PRs outstanding, we can auto-refactor those out.

2021-05-19 21:21 UTC, jonaskon requested changes
Some typos/improvements for the kdoc

2021-05-19 21:21 UTC, jonaskon commented on app/src/main/java/com/github/HumanLearning2021/HumanLearningApp/model/Category.kt
> + * @param name the name of the category (case-sensitive)
```suggestion
 * @property name the name of the category (case-sensitive)
```

2021-05-19 21:21 UTC, jonaskon commented on app/src/main/java/com/github/HumanLearning2021/HumanLearningApp/model/Category.kt
> + * @param id uniquely identifies the category
```suggestion
 * @property id uniquely identifies the category
```

2021-05-19 21:21 UTC, jonaskon commented on app/src/main/java/com/github/HumanLearning2021/HumanLearningApp/model/Category.kt
> + * @param representativePicture a categorized picture, can be null
```suggestion
```

2021-05-19 21:21 UTC, jonaskon commented on app/src/main/java/com/github/HumanLearning2021/HumanLearningApp/model/Dataset.kt
>   * @property id should be used to uniquely identify the Dataset
```suggestion
 * @property id uniquely identifies the Dataset
```

2021-05-20 09:03 UTC, jonaskon approved these changes

2021-05-20 12:46 UTC, Jaakik approved these changes

2021-05-20 13:27 UTC, merged