Flatten `CategorizedPicture` hierarchy
HumanLearning2021/HumanLearningApp pull request #181
Opened 2021-05-14 10:29 UTC by lourkeur

2021-05-18 15:29 UTC, lourkeur commented on app/src/main/java/com/github/HumanLearning2021/HumanLearningApp/firestore/FirestoreDatabaseService.kt
>          imageRef.putFile(picture).await()
Doesn't work if picture is a gs:// url.  I need to either fix or avoid this situation

2021-05-20 08:26 UTC, jonaskon requested changes

2021-05-20 08:26 UTC, jonaskon commented on app/src/main/java/com/github/HumanLearning2021/HumanLearningApp/firestore/FirestoreDatabaseService.kt
> +            Log.w(this.toString(), "Removing the image ${picture.id} from storage failed", e)
I don't agree with this change, the Firebase Storage does not store the id, hence it does not provide any information on which picture failed to be deleted if the picture already got deleted from the Firestore database.

2021-05-20 08:26 UTC, jonaskon commented on app/src/main/java/com/github/HumanLearning2021/HumanLearningApp/model/CategorizedPicture.kt
>   * Interface representing a categorized picture
```suggestion
 * Representation of a categorized picture
 * @property id unique identifier of the picture
 * @property category to which the picture is assigned
 * @property picture location of the drawable
```

2021-05-20 17:45 UTC, jonaskon approved these changes

2021-05-20 20:32 UTC, Jaakik approved these changes

2021-05-20 22:42 UTC, merged