Add missing kdoc
HumanLearning2021/HumanLearningApp pull request #225
Opened 2021-05-28 11:52 UTC by jonaskon

2021-05-28 15:38 UTC, lourkeur requested changes

2021-05-28 15:38 UTC, lourkeur commented on app/src/androidTest/java/com/github/HumanLearning2021/HumanLearningApp/hilt.kt
> -            .terminate() //TODO("Find out why it is initialized before this instead of just terminating it before restarting")
Do we not want TODO that anymore?

2021-05-28 15:38 UTC, lourkeur commented on app/src/androidTest/java/com/github/HumanLearning2021/HumanLearningApp/view/GoogleSignInFragmentTest.kt
> -class GoogleSignInWidgetTest {
:+1:

2021-05-28 15:38 UTC, lourkeur commented on app/src/main/java/com/github/HumanLearning2021/HumanLearningApp/model/UniqueDatabaseManagement.kt
>      fun removeDatabaseFromDownloadsAsync(databaseName: String) =
```suggestion
     * @return a job tracking completion of the operation
     */
    fun removeDatabaseFromDownloadsAsync(databaseName: String): Job =
```

2021-05-28 15:38 UTC, lourkeur commented on app/src/main/java/com/github/HumanLearning2021/HumanLearningApp/room/Daos.kt
> + * Data accessor object for everything concerning databases in on device storage
```suggestion
 * Data access object for everything concerning databases in on device storage
```

2021-05-30 14:28 UTC, jonaskon commented on app/src/androidTest/java/com/github/HumanLearning2021/HumanLearningApp/hilt.kt
> -            .terminate() //TODO("Find out why it is initialized before this instead of just terminating it before restarting")
Huh... I readded it

2021-06-02 14:07 UTC, Jaakik approved these changes
All good.  Just a reminder, I have added some Kdoc for the signIn Fragment

2021-06-03 06:46 UTC, lourkeur requested changes

2021-06-03 06:46 UTC, lourkeur commented on app/src/main/java/com/github/HumanLearning2021/HumanLearningApp/model/UniqueDatabaseManagement.kt
>      fun removeDatabaseFromDownloadsAsync(databaseName: String) =
please address this

2021-06-03 06:48 UTC, jonaskon commented on app/src/main/java/com/github/HumanLearning2021/HumanLearningApp/model/UniqueDatabaseManagement.kt
>      fun removeDatabaseFromDownloadsAsync(databaseName: String) =
I missed it sorry

2021-06-03 07:14 UTC, lourkeur approved these changes
LGTM. Just make sure not to re-add Statistic

2021-06-03 18:01 UTC, merged