Bug fix/privileges after signout
HumanLearning2021/HumanLearningApp pull request #234
Opened 2021-06-01 09:47 UTC by Jaakik

2021-06-01 15:17 UTC, Jaakik commented
@mlenw I didn't deal with the BackPress as it seemed to work fine When testing in on my phone, please request any changes you think are necessary in this regard.

2021-06-02 08:03 UTC, NicolasVial approved these changes
Looks good to me but... are you sure about the KDOC? I mean... I think Jonas have a PR to add all the missing KDoc ^^' we don't want to have conflicts in the KDoc I think :)

2021-06-02 12:07 UTC, mlenw requested changes
Back thing has an issue, and I agree with Nicolas about Kdoc. Need to be careful with merge conflicts. Other than that all good

2021-06-02 12:07 UTC, mlenw commented on app/src/main/res/navigation/nav_graph.xml
> +            app:destination="@id/homeFragment" />
```suggestion
            app:destination="@id/homeFragment"
            app:popUpTo="@+id/homeFragment"
            app:popUpToInclusive="true"
            />
```

2021-06-02 12:07 UTC, mlenw commented on app/src/main/res/navigation/nav_graph.xml
> +            app:destination="@id/homeFragment" />
When I press back it takes me back to login fragment. I think this should fix it.

2021-06-02 12:12 UTC, Jaakik commented
> Looks good to me but... are you sure about the KDOC? I mean... I think Jonas have a PR to add all the missing KDoc ^^' we don't want to have conflicts in the KDoc I think :)

Okay I will check that

2021-06-02 12:43 UTC, mlenw approved these changes

2021-06-02 13:53 UTC, merged